# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\first.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(220, 0, 581, 571))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.LeftGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.LeftGroupBox.setGeometry(QtCore.QRect(0, 0, 221, 571))
        self.LeftGroupBox.setObjectName("LeftGroupBox")
        self.searchField = QtWidgets.QTextEdit(self.LeftGroupBox)
        self.searchField.setGeometry(QtCore.QRect(10, 10, 201, 31))
        self.searchField.setObjectName("searchField")
        self.chat_area = QtWidgets.QScrollArea(self.LeftGroupBox)
        self.chat_area.setGeometry(QtCore.QRect(10, 50, 201, 521))
        self.chat_area.setAutoFillBackground(False)
        self.chat_area.setWidgetResizable(True)
        self.chat_area.setObjectName("chat_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 199, 519))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.chat_area.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.button_add = QtWidgets.QMenu(self.menubar)
        self.button_add.setObjectName("button_add")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_add_friend = QtWidgets.QAction(MainWindow)
        self.action_add_friend.setObjectName("action_add_friend")
        self.action_add_chat = QtWidgets.QAction(MainWindow)
        self.action_add_chat.setObjectName("action_add_chat")
        self.action_addconversation = QtWidgets.QAction(MainWindow)
        self.action_addconversation.setObjectName("action_addconversation")
        self.button_add.addAction(self.action_add_friend)
        self.button_add.addAction(self.action_add_chat)
        self.button_add.addAction(self.action_addconversation)
        self.menubar.addAction(self.button_add.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LeftGroupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.button_add.setTitle(_translate("MainWindow", "Добавить"))
        self.action_add_friend.setText(_translate("MainWindow", "Друга"))
        self.action_add_chat.setText(_translate("MainWindow", "Чат"))
        self.action_addconversation.setText(_translate("MainWindow", "Беседу"))
